var produtos = [
  {
    id: 1,
    titulo: "Combo Royal",
    descricao: "4 deleciosas coxinhas + 1 Guaraná de 1L",
    preco: 18.0,
    imagem: "./../imagens/comboroyal.png",
    categoria: ["Combo"],
    quantidade: 0,
  },
  {
    id: 6,
    titulo: "Combo Galera",
    descricao: "10 deleciosas coxinhas + 1 refri de 350ml",
    preco: 18.0,
    imagem: "./../imagens/ComboGalera.png",
    categoria: ["Combo"],
    quantidade: 0,
  },
  {
    id: 2,
    titulo: "Coxinha de Frango",
    descricao: "Deliciosa coxinha recheado com frango cremoso",
    preco: 3.5,
    imagem: "./../imagens/coxinhafrango.png",
    categoria: ["Salgado", "Coxinha"],
    quantidade: 0,
  },
  {
    id: 3,
    titulo: "Empada de Frango",
    descricao: "Deliciosa empada recheado com frango cremoso",
    preco: 5.0,
    imagem: "./../imagens/empada.png",
    categoria: ["Salgado", "Empada"],
    quantidade: 0,
  },
  {
    id: 4,
    titulo: "Bola de Queijo",
    descricao: "Deliciosa bola de queijo",
    preco: 3.5,
    imagem: "./../imagens/boladequeijo.png",
    categoria: ["Salgado"],
    quantidade: 0,
  },
  {
    id: 5,
    titulo: "Quibe com Queijo",
    descricao: "Deliciosa quibe rejeado com Queijo",
    preco: 5.0,
    imagem: "./../imagens/quibe.png",
    categoria: ["Salgado", "Quibe"],
    quantidade: 0,
  }
];
